### ISSUE TITLE
Error in inflow data loading

### ISSUE THREAD

**Issue by tanagarth79** [aemon-j/LakeEnsemblR#250]
Hi everybody!

I have an issue during the setting up phase for my lake. Setting export go well, but when I try to run the ensemble lake models I get the following:

**_Loading inflow data...
Error in inflow_start:inflow_stop : argument of length 0_**

My lake has four inflows and one outflow. I checked input files and they seem ok.

Thanks in advance for your help!

**Comment by jorritmesman** [comment]
Hi!

Did you manage to run the ensemble without in- or outflows? Just to make sure the problem is just with the in- and outflows...

I suspect there is some issue with reading the inflow file. Are you sure the name of your inflow file is correct and that the format is similar to this file: https://raw.githubusercontent.com/aemon-j/LakeEnsemblR/main/inst/extdata/feeagh/LakeEnsemblR_inflow_standard.csv. So: comma-separated, same datetime format, same column headers (up to 4, in your case)?

Just let us know if your problems persist. If so, could you attach your LakeEnsemblR config file and maybe the first 5 lines of your inflow file?

**Comment by tanagarth79** [comment]
Hello Jorrit!

I did not try yet to run the model without in/outflows but I can check it also. I had a look at the inflow file and compared it to the format you sent me, and it looks correct so far. I attached to this message the config file (changed to .txt so that I can add it to this message) and inflow subset.

Thanks in advance for your help!

[vortsjarv5lines_inflow_standard.csv](https://github.com/aemon-j/LakeEnsemblR/files/9532749/vortsjarv5lines_inflow_standard.csv)
[vortsjarv.txt](https://github.com/aemon-j/LakeEnsemblR/files/9532754/vortsjarv.txt)

**Comment by JFeldbauer** [comment]
Hello,
I think the problem is that you set the end date of your simulation to 2015-01-31 21:00:00. The models included in LakeEnsemblR only can handle in and outflow with daily time step. We did not check using a end date at temporal respolution and I guess we should include a check or rounding of the end date for the flow formatting.
I would suggest for now that you set your end date to either 2015-01-31 00:00:00 or 2016-01-01 00:00:00 and see if it will run

**Comment by tanagarth79** [comment]
Hello,

I changed the end date to 2015-01-31 00:00:00 and it doesn't display this error anymore, thanks a lot!

**Comment by jorritmesman** [comment]
Great this was fixed! I don't think the hourly specification was the problem per se, but rather the line `inflow_stop <- which(inflow$datetime == as.POSIXct(stop_date))`. So the stop date needs to occur in the inflow file, otherwise this error is generated. This is something we could try to improve, but until then this is a good way of avoiding the problem.

**Comment by JFeldbauer** [comment]
> Great this was fixed! I don't think the hourly specification was the problem per se, but rather the line `inflow_stop <- which(inflow$datetime == as.POSIXct(stop_date))`. So the stop date needs to occur in the inflow file, otherwise this error is generated. This is something we could try to improve, but until then this is a good way of avoiding the problem.

you are right. in any case we should fix this some time soon

**Comment by tanagarth79** [comment]
Thank you Jorrit for the explanation, I will run the model with these settings. I also check carefully each time I open the .csv files in Excel that I re-format the dates to LakeAnalyzR format because Excel stubbornly switches them back to dd-mm-yy format.
