### ISSUE TITLE
Strange water mass balance behavior in Simstrat model

### ISSUE THREAD

**Issue by JorgeMonPe** [aemon-j/LakeEnsemblR#253]
Hi everybody,
First of all, thank you very much for developing this useful R package.
I'm running the package with data from a reservoir which has water level fluctuations and I found a strange behavior in Simstrat model (GLM and GOTM go well).
I tested it with the example (feeagh lake) and the problem come up when there is a change in depths of one water temperature profile in the observations wtemp profiles. 

<h3>Using feeagh example to reproduce the issue</h3>

I increased the outflow, multiplying by 2 the standard outflow, in order to appreciate a water level change in the lake ([LakeEnsemblR_outflow_standard_higher.csv](https://github.com/aemon-j/LakeEnsemblR/files/9808811/LakeEnsemblR_outflow_standard_higher.csv)).[](url)
Then I ran the model and water level change is similar in GOTM and Simstrat model.
![ensemble_heatmap_higheroutflow](https://user-images.githubusercontent.com/29984952/196390740-8380ff96-c3ff-44e5-ab3f-0a9c1b0e2834.png)

Then, I modified one temperature profile in the wtemp_profile_standard file ([LakeEnsemblR_wtemp_profile_standard_modified.csv](https://github.com/aemon-j/LakeEnsemblR/files/9808839/LakeEnsemblR_wtemp_profile_standard_modified.csv)). The only change is that in the profile of day 2010-03-05, depths were modified from c(0.9,2.5,5,8,11,14,16,18,20,22,27,32,42) to c(0.6,2,6.3,8.6,11,13.2,16.6,18,19.2,21.7,28.2,32.3,42).
And the output of the model show a big step in water level at the beginning of the simulation period.
![ensemble_heatmap_modified_wtemp_profile](https://user-images.githubusercontent.com/29984952/196392821-6c7b008e-84e7-4a1e-986a-584ef21b0fe3.png)

I checked all input files for the Simstrat model and they look fine. The problem seems to be related to new depths in observed profiles but I don't know how this is affecting water balance in Simstrat model.
Any idea of what could be happening?
Thank you in advance!

**Comment by JorgeMonPe** [comment]
Thank for your prompt response!
Here is the plot with the water level, which looks ok:
![water_level](https://user-images.githubusercontent.com/29984952/196455587-024d24f5-de2a-4a5a-aa53-d980406c6852.png)


but the .csv doesn't show that:
[Feeagh_Simstrat_temp.csv](https://github.com/aemon-j/LakeEnsemblR/files/9811313/Feeagh_Simstrat_temp.csv) 
Vs
[Feeagh_GOTM_temp.csv](https://github.com/aemon-j/LakeEnsemblR/files/9811318/Feeagh_GOTM_temp.csv)

**Comment by jorritmesman** [comment]
Alright, I managed to reproduce the problem and I figured out what the issue was (probably)! In `get_output.R` (used in `run_ensemble` to get the data from all the models into a common format), in L. 379-381 (for Simstrat), we tried to set all values below the water level to `NA`. However, we made the mistake of using the index of the temperature output of the model, whereas we should have checked at what depth the output should be `NA` and from that compute the index in `wat_mat` from which the values should become `NA`, because here we interpolate the model results to include all the values in the temperature observations file (and you added unique depths to the observations in your example). 

I will change these lines (and a similar line for the density extraction) to:
```
if (any(is.na(y))){
    # Set values to NA from this index onwards
    min_depth_na <- mod_depths[min(which(is.na(y)))]
    min_ind_na <- min(which(depths <= min_depth_na))
    wat_mat[i, (min_ind_na : length(wat_mat[i, ]))] <- NA
}
```

I want our automated tests to first check the code and I'll simultaneously try to fix another Issue, and I will not be at work tomorrow, but depending on when the changes and tests are finished, I'll try to update the repository today or Friday, and I'll close this Issue when that's done. Of course feel free to re-open if the problem persists. 

Thank you very much for finding this bug and contacting us about this! This helps us to continue improving the code!

**Comment by JorgeMonPe** [comment]
Great! Thanks to you for finding and resolving the bug!

**Comment by jorritmesman** [comment]
There are some unexpected issues with install dependencies during the tests, but in case you want to use an updated version, you can use this one: https://github.com/jorritmesman/LakeEnsemblR

**Comment by jorritmesman** [comment]
Now the changes have been merged into main

**Comment by JorgeMonPe** [comment]
Great new! Thank you very much Jorrit.
