### ISSUE TITLE
issue in high-latitude lake modeling

### ISSUE THREAD

**Issue by lifewangyiming** [aemon-j/LakeEnsemblR#276]
When I used LakeEnsemblR to model high-latitude lakes, there were warnings from the _export_config_  function and caused wrongs in MyLake model. I checked the source code of _export_config_ and found that there may be something wrong when using the _gotmtools::calc_cc_ function to calculate the cloud cover for solar radiation. Because the code used to calculate the solar zenith angle went wrong  when it was polar day/night:

```
yday <- yday(date)
hour <- hour(date)
hour[hour == 0] <- 24
std.mer = seq(-90, 90, 15)
Lsm = std.mer[which.min(abs(lon - std.mer))]
Hsc = 1390
cd = 0.06
Rg = 0.045
theta = lat * pi/180
r = 1 + 0.017 * cos((2 * pi/365) * (186 - yday))
d = 23.45 * pi/180 * cos((2 * pi/365) * (172 - yday))
dts = (1/15) * (Lsm - lon)
value = (sin(theta) * sin(d))
value = value/(cos(theta) * cos(d))
tss = (12/pi) * acos(-value) + dts + 12
tsu = -tss + (2 * dts) + 24
gamma = rep(0, length(tss))
dum = which(hour > tsu & hour < tss)
gamma[dum] = 1
dum1 = which(hour <= 12)
dum2 = which(hour > 12)
hb1 = pi/12 * (hour - 1 - dts)
hb1[dum1] = hb1[dum1] + pi
hb1[dum2] = hb1[dum2] - pi
hb = hb1
dum3 = which(hb1 > 2 * pi)
hb[dum3] = hb[dum3] - 2 * pi
dum4 = which(hb1 < 0)
hb[dum4] = hb[dum4] + 2 * pi
he1 = pi/12 * (hour - dts)
he1[dum1] = he1[dum1] + pi
he1[dum2] = he1[dum2] - pi
he = he1
dum3 = which(he1 > 2 * pi)
he[dum3] = he[dum3] - 2 * pi
dum4 = which(he1 < 0)
he[dum4] = he[dum4] + 2 * pi
Ho = Hsc/(r^2) * (sin(theta) * sin(d) + 12/pi * cos(theta) * 
cos(d) * (sin(he) - sin(hb))) * gamma
w = (he + hb)/2
alpha1 = abs(sin(theta) * sin(d) + cos(theta) * cos(d) * 
cos(w))
alpha = atan(alpha1/sqrt(1 - alpha1^2))
```

The variable _value_ could exceed the range of [-1,1] in ploar day/nights so that acos(-value) would return NAs

**Comment by jorritmesman** [comment]
Thanks for letting us know about this issue. Together with the information you sent by email, I looked a bit further into this issue. As you stated there already, although the `calc_cc` function is throwing warnings due to the high latitude, the cloud cover during the polar nights is set to 1, which does not prevent the models from running (you could provide your own cloud cover estimation for a more correct estimate). However, MyLake is still encountering an error.

After running `export_config`, I could remove the error by lowering latitude in the MyLake config file (loading the mylake.Rdata file, changing `mylake_config$Phys.par[6,]`, and saving it again) below 67 degrees, and running it again. So everything else, including meteorology, remained the same. 

As you had already found, the error happened inside the Ppart function, and I think I further narrowed it down to where the problem starts to occur: the `heatflux_v12` function (line 275 in the Rlake_main.R script). What seems to happen, is that the sun is below the horizon all day, therefore all values of `alt` are negative, therefore `DayFrac` is set to 0, which in the Rlake_main script, in L. 300-308, causes a division by 0 and eventually NA values for PAR and an error message later on. 

Since this issue is specific to the MyLake code, there is not much we can directly do about this, but we will reach out to people that have actively worked with MyLake (@rmpilla). The R MyLake code is from an older version and the model has seen continued development in Matlab, so perhaps this issue has already been fixed there. 

In the meantime, you could either remove MyLake from the model run (the other models in your example seemed to run fine, although the GLM output looked unrealistic). Otherwise, you could do what I did and after running `export_config`, set latitude to 66 degrees and hope this doesn't affect the thermal structure too much. I will leave this comment open so people are aware, and perhaps the MyLake code can be changed to avoid this error.

**Comment by lifewangyiming** [comment]
Thanks for your comment. As the _Qlw_ (long-wave radiation) in MyLake was calculated by cloud cover, using the `blwhf` function, I will change the input from long-wave radiation to cloud cover to better round the MyLake model (beacuse CC=1 in polar night isn't very realistic although it works) and do what you recommened. Thank you!

**Comment by lifewangyiming** [comment]
Thanks for your comment. As the Qlw (long-wave radiation) in MyLake was calculated by cloud cover, using the blwhf function, I will change the input from long-wave radiation to cloud cover to better round the MyLake model (beacuse CC=1 in polar night isn't very realistic although it works) and do what you recommened. Thank you!

**Comment by jorritmesman** [comment]
I updated the MyLake code (https://github.com/aemon-j/MyLakeR/pull/9); now during a polar night, the entire PAR profile is set to 0. I ran some tests and at lower latitude lakes, the model behaves the same, while it no longer crashes at higher latitudes.
