### ISSUE TITLE
Add equation to convert Kw to e-folding depth for GOTM

### ISSUE THREAD

**Issue by tadhg-moore** [aemon-j/LakeEnsemblR#36]
Currently there is only Kw input in the config file. Neccessary to add a conversion equation, one that was used in ISIMIP.
Would be useful to include secchi_depth as an input parameter in the config file

**Comment by tadhg-moore** [comment]
@JFeldbauer  added the conversion in #37 so next will be the secchi depth in the config file and then the conversions from secchi depth.

**Comment by jorritmesman** [comment]
Conversion of Kw to e-folding depth in GOTM (g2) complete, also for time series (see export_extinction). 

Conversion from secchi depth not implemented (yet), due to often different equations per lake (e.g. depending on DOC content). In the vignette, we could potentially give links/tips for conversion, but implementation in code is not planned.
