### ISSUE TITLE
Lake timezone setting

### ISSUE THREAD

**Issue by tadhg-moore** [aemon-j/LakeEnsemblR#46]
Figure out how to deal with lakes in different timezones for example timezone is a parameter in glm.nml and GOTM expects all the data to be in UTC. This will be important for input data (wtemp profiles) and also output data particularly when working on sub-daily timescales. This could also feed into #45 as it will be neccessary when calculating hourly met data from daily data.

**Comment by jorritmesman** [comment]
Would be good to make a list of how the different models use time zone data, most notably GOTM and GLM. I imagine it is mostly used for filling in missing meteorological data (incoming shortwave, longwave maybe). 

If that's the case, I would prefer that we leave that responsibility with the users. The ensemble tool is not really meant to fill in missing data, especially because different models would tend to do this differently! And then it wouldn't matter what time zone the user fills in, UTC or otherwise. 

For #45 it would indeed be important to know the time zone. This should be an obligatory argument in the function. If we are afraid of mistakes by the user, we could provide no default; then the user has to consciously fill in the time zone.

**Comment by jorritmesman** [comment]
Currently, it does not matter what time zone the input files are in, as long as albedo_mode in GLM is not set to "2" or "3", in which case the time zone needs to be UTC. The following text has been added to the vignette:

"LakeEnsemblR will work with any time zone, provided that the time columns in all input files are in the same time zone and there are no shifts from/to daylight saving time in the files. Of all models, only GLM requires to know the time zone. In LakeEnsemblR this is automatically set to UTC. However, this information is only used in GLM's `albedo_mode` 2 and 3, or when GLM's `rad_mode` is set to 5 (i.e. computing shortwave radiation if this is not provided). In LakeEnsemblR, the default `albedo_mode` is 1, and shortwave radiation must be provided, so providing the timezone is not required. Yet if you are changing `albedo_mode` to 2 or 3, make sure you enter your data in UTC. GOTM also assumes the time to be in UTC, but this is only used when computing shortwave radiation if it is not provided, which does not happen when using LakeEnsemblR."
