### ISSUE TITLE
rlang and (maybe) gotmtools

### ISSUE THREAD

**Issue by jjvenky** [aemon-j/LakeEnsemblR#58]
After https://github.com/aemon-j/LakeEnsemblR/issues/55

From time-to-time I have had issues with `rlang` versions and it appeared here. Appears to be an issue with https://github.com/aemon-j/gotmtools but I only needed gotmtools to build LakeEnsemblR.

```
Loading required package: rLakeAnalyzer
Error: package or namespace load failed for ‘gotmtools’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.4.1 is already loaded, but >= 0.4.2 is required
```

Fixed with `install.packages("rlang")` and thus and update to 0.4.4.

**Comment by jread-usgs** [comment]
I think this is an expected and useful error - the package sets the minimum expected version of a dependency, and if your install doesn't meet it, you get a helpful error message that encourages you to update the dependency. Are you suggesting something within LakeEnsemblR should change to fix this error?

**Comment by jjvenky** [comment]
@jread-usgs Should this be in the `Imports` section of the `DESCRIPTION` file since there is a specific package and version requirement?

**Comment by jread-usgs** [comment]
If it is a requirement for `gotmtools`, yes, it should be in the DESCRIPTION - but that should be specified in the package that _needs_ the version, not the package that depends on the package that needs that version. So I'd say if it is gotmtools that needs rlang >= 0.4.2, it should be specified in that pkg's DESCRIPTION file. That will also make it necessary version in order to to use LakeEnsemblR, but, if gotmtools changes in the background and no longer needs that version (or needs 0.5.0 or something...) it has the control over specifying it, as opposed to being handled in this pkg and risking going out of date w/ the true dependency.

**Comment by jjvenky** [comment]
Thanks @jread-usgs.

PR now in https://github.com/aemon-j/gotmtools/pull/5
